CREATE TABLE IF NOT EXISTS Station
(
Station_ID INT PRIMARY KEY,
von_datum DATE,
bis_datum DATE,
Stattionhoehe INTEGER,
geoBreite REAL,
geoLaenge REAL,
Stationsname TEXT,
Bundesland TEXT
);

CREATE TABLE IF NOT EXISTS Measurement
(
m_ID INTEGER PRIMARY KEY,
Station_ID INTEGER,
MESS_DATUM DATE,
QN_3 INTEGER,
FX REAL,
FM REAL,
QN_4 INTEGER,
RSK REAL,
RSKF INTEGER,
SDK REAL,
SHK_TAG REAL,
NM REAL,
VPM REAL,
PM REAL,
TMK REAL,
UPM REAL,
TXK REAL,
TNK REAL,
TGK REAL,
FOREIGN KEY (Station_ID) REFERENCES Station(Station_ID)
);

CREATE TABLE IF NOT EXISTS Parameter
(
Parameter_ID SERIAL PRIMARY KEY,
Parameter_Name TEXT,
Parameter_Description TEXT,
Unit TEXT
);
