# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy files required for installation
COPY requirements.txt setup.py ./

# Install dependencies
RUN pip install --no-cache-dir -ra requirements.txt \
&& pip install -e .


# Copy the rest of the application
COPY config.yaml Create_table.sql main.py ./
COPY data_ingestion ./data_ingestion/

# Entrypoint for the ingestion service
# This container will run the data ingestion command
ENTRYPOINT ["dwd-ingest"]
